# Official Go image based on Alpine
FROM golang:1.22-alpine

RUN apk add --no-cache bash git

WORKDIR /app

# Keep the container running indefinitely so it can be attached to
CMD ["sleep", "infinity"]