# Official Go image based on Alpine
FROM golang:1.22-alpine

WORKDIR /app

# Using --no-cache keeps the image layer small.
RUN apk add --no-cache python3

# Keep the container running indefinitely
CMD ["sleep", "infinity"]