# --- Stage 1: The Builder ---
FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY main.go .

# We will copy the output 'main.wasm' file into the next image.
RUN GOOS=js GOARCH=wasm go build -o main.wasm main.go

# --- Stage 2: The Production Image ---
FROM alpine:latest

# Install Python for serving web files
RUN apk add --no-cache python3

WORKDIR /app

# Copy front-end files
COPY index.html .
COPY main.js .

# Copy the WebAssembly files from build stage
COPY --from=builder /go/misc/wasm/wasm_exec.js .
COPY --from=builder /app/main.wasm .

# Expose port 8000 to the local machine
EXPOSE 8000

# Starts a web server on localhost:8000 serving index.html
CMD ["python3", "-m", "http.server", "8000"]
